[theme]
primaryColor = "#0891b2"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#09090b"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
